# Generated by Django 3.1.6 on 2022-01-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('projects', '0002_auto_20211231_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='interests',
            field=models.ManyToManyField(blank=True, to='interests.Interest'),
        ),
    ]
