# Generated by Django 3.1.6 on 2022-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommended_count',
            field=models.IntegerField(default=0),
        ),
    ]
